
name: github pages
on:
  push:
    branches: [ main, contruct-repo ] # TODO: remove test repo soon
  pull_request: # Comment this out soon
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm install  --prefix rmf_panel
          npm run build  --prefix rmf_panel
      - name: trim
        run: |
          mkdir .public
          mv -r rmf_panel/dist .public/
          mv rmf_panel/index.html .public
      - name: deploy_page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .public
